import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Url Shortener',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className=' w-full min-h-screen mx-auto p-0 sm:px-16 flex flex-col justify-between'>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
